// contains all cars
const cars = [
  {
    id: 1,
    name: "Maruti Suzuki Dzire",
    type: "Sedan",
    price: 2000,
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "assets/images/cars/dezire.png",
  },
  {
    id: 2,
    name: "Volkswagen Virtus",
    type: "Sedan",
    price: 3500,
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "assets/images/cars/virtus.png",
  },
  {
    id: 3,
    name: "Skoda Slavia",
    type: "Sedan",
    price: 3500,
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "assets/images/cars/slavia.png",
  },
  {
    id: 4,
    name: "Toyota Camry",
    type: "Sedan",
    price: 5500,
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "assets/images/cars/toyota_camry.png",
  },
  {
    id: 5,
    name: "BMW X3",
    type: "SUV",
    price: 7000,
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "assets/images/cars/bmw_x3.png",
  },
  {
    id: 6,
    name: "Mercedes-Benz C-Class",
    type: "Sedan",
    price: 7500,
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "assets/images/cars/mercedes_c_class.png",
  },
  {
    id: 7,
    name: "Land Rover Defender",
    type: "SUV",
    price: 9000,
    seats: 5,
    transmission: "Automatic",
    fuel: "Diesel",
    image: "assets/images/cars/defender.png",
  },
  {
    id: 8,
    name: "Tata Safari",
    type: "SUV",
    price: 4500,
    seats: 7,
    transmission: "Automatic",
    fuel: "Diesel",
    image: "assets/images/cars/safari.png",
  },
  {
    id: 9,
    name: "Maruti Suzuki Ertiga",
    type: "MPV",
    price: 3000,
    seats: 7,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "assets/images/cars/ertiga.png",
  },
  {
    id: 10,
    name: "Toyota Innova Hycross",
    type: "MPV",
    price: 5000,
    seats: 7,
    transmission: "Automatic",
    fuel: "Hybrid",
    image: "assets/images/cars/innova.png",
  },
];
